
##Set global url here
@baseUrl = http://localhost:2507/api


###
GET  {{baseUrl}}/u
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1NzgzNDkxMjcsImV4cCI6MTU3ODM1MjcyN30.SQaxnNNXHE6tG2MEmYxCuj4OXOez06KYcQXjcWjJE-U

###
POST {{baseUrl}}/register-user HTTP/1.1
content-type: application/json

{
  "username": "tp",
  "email_address": "tipain@imprint",
  "contact": "0772275148v",
  "user_password": "P@zzW0rD!!",
  "is_active": true
}

###  login 
POST {{baseUrl}}/user/login HTTP/1.1
content-type: application/json

{
      "username": "tpainv",
      "user_password": "P@zzW0rD!!"
}

